/**
 * Mock Data Service for AI-Driven Personalized Promotion and Inventory Alignment Planner
 * Standardized in INR (₹) with realistic Indian retail/e-commerce data.
 */

export const INITIAL_PRODUCTS = [
  {
    id: 'prod-1',
    sku: 'ELEC-SNY-101',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    category: 'Electronics',
    costPrice: 19500,
    sellingPrice: 29990,
    currentStock: 145,
    reorderThreshold: 40,
    dailyVelocity: 4.8,
    leadTimeDays: 7,
    rating: 4.8,
    reviewCount: 1420,
    image: '🎧',
    status: 'healthy',
    description: 'Industry-leading noise canceling headphones with 30hr battery life and crystal clear hands-free calling.',
    historicalMonthlyUnits: 144,
  },
  {
    id: 'prod-2',
    sku: 'FASH-FAB-204',
    name: 'FabIndia Pure Linen Handcrafted Kurta',
    category: 'Fashion',
    costPrice: 1100,
    sellingPrice: 2899,
    currentStock: 320,
    reorderThreshold: 100,
    dailyVelocity: 12.5,
    leadTimeDays: 10,
    rating: 4.6,
    reviewCount: 890,
    image: '👔',
    status: 'healthy',
    description: 'Breathable 100% pure organic linen kurta with intricate wooden buttons and comfort regular fit.',
    historicalMonthlyUnits: 375,
  },
  {
    id: 'prod-3',
    sku: 'HOME-PHI-309',
    name: 'Philips Digital Air Fryer HD9252 (4.1L)',
    category: 'Home & Kitchen',
    costPrice: 4800,
    sellingPrice: 8499,
    currentStock: 28,
    reorderThreshold: 35,
    dailyVelocity: 3.2,
    leadTimeDays: 14,
    rating: 4.7,
    reviewCount: 2310,
    image: '🍳',
    status: 'low',
    description: 'Rapid Air Technology with touchscreen display and 7 preset cooking programs for healthy frying.',
    historicalMonthlyUnits: 96,
  },
  {
    id: 'prod-4',
    sku: 'BEAU-FOR-405',
    name: 'Forest Essentials Ayurvedic Advanced Soundarya Serum',
    category: 'Beauty & Personal Care',
    costPrice: 1800,
    sellingPrice: 4200,
    currentStock: 85,
    reorderThreshold: 30,
    dailyVelocity: 2.8,
    leadTimeDays: 5,
    rating: 4.9,
    reviewCount: 640,
    image: '✨',
    status: 'healthy',
    description: 'Traditional 24K gold infused face serum for deep radiance and anti-aging cell rejuvenation.',
    historicalMonthlyUnits: 84,
  },
  {
    id: 'prod-5',
    sku: 'ELEC-1PL-108',
    name: 'OnePlus Nord Buds 3 Pro ANC Earbuds',
    category: 'Electronics',
    costPrice: 1650,
    sellingPrice: 3299,
    currentStock: 12,
    reorderThreshold: 50,
    dailyVelocity: 8.4,
    leadTimeDays: 6,
    rating: 4.5,
    reviewCount: 3100,
    image: '🎵',
    status: 'critical',
    description: '49dB Hybrid Active Noise Cancellation with BassWave 2.0 dynamic acoustic engineering.',
    historicalMonthlyUnits: 252,
  },
  {
    id: 'prod-6',
    sku: 'GROC-SLP-502',
    name: 'Sleepy Owl Cold Brew Dark Roast Brew Packs (Pack of 5)',
    category: 'Groceries & Gourmet',
    costPrice: 320,
    sellingPrice: 650,
    currentStock: 480,
    reorderThreshold: 120,
    dailyVelocity: 18.0,
    leadTimeDays: 3,
    rating: 4.7,
    reviewCount: 4200,
    image: '☕',
    status: 'healthy',
    description: '100% Arabica artisanal beans sourced from Chikmagalur estates for smooth 24-hour steeping.',
    historicalMonthlyUnits: 540,
  },
  {
    id: 'prod-7',
    sku: 'FASH-PUM-211',
    name: 'Puma Velocity Nitro 3 Road Running Shoes',
    category: 'Fashion',
    costPrice: 4200,
    sellingPrice: 8999,
    currentStock: 42,
    reorderThreshold: 60,
    dailyVelocity: 4.1,
    leadTimeDays: 12,
    rating: 4.6,
    reviewCount: 512,
    image: '👟',
    status: 'low',
    description: 'Advanced nitrogen-injected foam cushioning with durable Pumagrip rubber outsole traction.',
    historicalMonthlyUnits: 123,
  },
  {
    id: 'prod-8',
    sku: 'HOME-PRE-314',
    name: 'Prestige Induction Cooktop PIC 20.0 (2000W)',
    category: 'Home & Kitchen',
    costPrice: 1550,
    sellingPrice: 2895,
    currentStock: 0,
    reorderThreshold: 45,
    dailyVelocity: 5.5,
    leadTimeDays: 8,
    rating: 4.3,
    reviewCount: 1890,
    image: '⚡',
    status: 'out_of_stock',
    description: 'Indian menu options with dual heat sensors and automatic voltage regulator protection.',
    historicalMonthlyUnits: 165,
  },
  {
    id: 'prod-9',
    sku: 'BEAU-MIN-412',
    name: 'Minimalist 10% Niacinamide Face Serum with Zinc (30ml)',
    category: 'Beauty & Personal Care',
    costPrice: 210,
    sellingPrice: 599,
    currentStock: 540,
    reorderThreshold: 150,
    dailyVelocity: 22.0,
    leadTimeDays: 4,
    rating: 4.8,
    reviewCount: 8950,
    image: '🧴',
    status: 'healthy',
    description: 'Pure Grade Niacinamide with EU sourced Zinc PCA to reduce blemishes and balance sebum.',
    historicalMonthlyUnits: 660,
  },
  {
    id: 'prod-10',
    sku: 'ELEC-BOAT-115',
    name: 'boAt Stone 1200 14W Portable Bluetooth Speaker',
    category: 'Electronics',
    costPrice: 1450,
    sellingPrice: 3499,
    currentStock: 210,
    reorderThreshold: 70,
    dailyVelocity: 9.0,
    leadTimeDays: 5,
    rating: 4.4,
    reviewCount: 4520,
    image: '🔊',
    status: 'healthy',
    description: 'RGB LEDs, IPX7 water resistance, 360 degree stereo sound with 9 hours continuous playtime.',
    historicalMonthlyUnits: 270,
  },
  {
    id: 'prod-11',
    sku: 'GROC-ORG-508',
    name: 'Organic India Tulsi Sweet Rose Infusion (Pack of 3)',
    category: 'Groceries & Gourmet',
    costPrice: 310,
    sellingPrice: 699,
    currentStock: 390,
    reorderThreshold: 100,
    dailyVelocity: 14.2,
    leadTimeDays: 4,
    rating: 4.8,
    reviewCount: 2780,
    image: '🍵',
    status: 'healthy',
    description: 'Certified organic whole herbal infusion combining sacred Tulsi and fragrant organic rose petals.',
    historicalMonthlyUnits: 426,
  },
  {
    id: 'prod-12',
    sku: 'BEAU-BSC-420',
    name: 'Bombay Shaving Company Premium Charcoal Shaving Kit',
    category: 'Beauty & Personal Care',
    costPrice: 580,
    sellingPrice: 1499,
    currentStock: 65,
    reorderThreshold: 80,
    dailyVelocity: 3.5,
    leadTimeDays: 7,
    rating: 4.5,
    reviewCount: 1140,
    image: '🪒',
    status: 'low',
    description: 'Complete 5-step salon shaving regimen with activated charcoal scrub, shaving foam and post-shave balm.',
    historicalMonthlyUnits: 105,
  }
];

export const INITIAL_SEGMENTS = [
  {
    id: 'frequent_buyers',
    name: 'Loyal Frequent Shoppers',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    icon: 'Repeat',
    customerCount: 28450,
    customerSharePercent: 24.2,
    aov: 2850,
    annualOrders: 18.4,
    elasticityCoefficient: 0.65, // Moderate elasticity: value consistent reliability
    marginTolerance: 'High',
    preferredCategories: ['Groceries & Gourmet', 'Beauty & Personal Care', 'Fashion'],
    retentionRate: 84.5,
    summary: 'High-frequency shoppers with steady brand trust. Responsive to bundle discounts and loyalty point multipliers without requiring heavy price slashes.',
    recommendedPromoStrategy: 'Tiered volume discounts (e.g. Buy 2 Get 10% Off) or Exclusive Member bundles. Avoid deep discounts that erode margin unnecessarily.'
  },
  {
    id: 'high_value_vips',
    name: 'High-Value VIPs & Affluent',
    badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    icon: 'Crown',
    customerCount: 12600,
    customerSharePercent: 10.7,
    aov: 14200,
    annualOrders: 4.8,
    elasticityCoefficient: 0.35, // Low elasticity: driven by quality, novelty, premium service
    marginTolerance: 'Very High',
    preferredCategories: ['Electronics', 'Home & Kitchen', 'Fashion'],
    retentionRate: 91.2,
    summary: 'Affluent cohort with substantial basket sizes and lowest price sensitivity. Highly responsive to new launches, early access, and premium bundles.',
    recommendedPromoStrategy: 'Low discount (5% - 10%) with value-adds, premium complimentary samples, or high-tier cashbacks on purchases above ₹15,000.'
  },
  {
    id: 'occasional_shoppers',
    name: 'Occasional & Seasonal Shoppers',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
    icon: 'Calendar',
    customerCount: 45800,
    customerSharePercent: 39.0,
    aov: 3400,
    annualOrders: 2.1,
    elasticityCoefficient: 0.95, // Balanced elasticity
    marginTolerance: 'Medium',
    preferredCategories: ['Fashion', 'Home & Kitchen', 'Electronics'],
    retentionRate: 52.0,
    summary: 'Festival and holiday shoppers who buy 2-3 times a year during major sale events. Need compelling contextual hooks to convert off-season.',
    recommendedPromoStrategy: 'Targeted 15% - 20% seasonal discounts, category cross-sells, and limited-time 48-hour flash offers.'
  },
  {
    id: 'discount_sensitive',
    name: 'Bargain & Promo Hunters',
    badgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
    icon: 'Zap',
    customerCount: 22400,
    customerSharePercent: 19.1,
    aov: 1950,
    annualOrders: 3.5,
    elasticityCoefficient: 1.85, // High elasticity: massive spike with >20% discounts
    marginTolerance: 'Low',
    preferredCategories: ['Beauty & Personal Care', 'Electronics', 'Groceries & Gourmet'],
    retentionRate: 38.6,
    summary: 'Price-elastic cohort looking for maximum percentage markdowns. Highly active during clearance events, but easily causes inventory drains.',
    recommendedPromoStrategy: 'Use strategically (25% - 35% discount) to liquidate overstocked inventory or slow-moving SKUs with high stock buffer.'
  },
  {
    id: 'churn_risk',
    name: 'Lapsed & At-Risk Customers',
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    icon: 'UserMinus',
    customerCount: 8250,
    customerSharePercent: 7.0,
    aov: 2900,
    annualOrders: 0.8,
    elasticityCoefficient: 1.40,
    marginTolerance: 'Medium',
    preferredCategories: ['Fashion', 'Beauty & Personal Care', 'Groceries & Gourmet'],
    retentionRate: 15.2,
    summary: 'Previously active customers who have not transacted in 90+ days. Require personalized reactivation incentives to re-enter purchase funnel.',
    recommendedPromoStrategy: 'Special "We Miss You" 20% discount coupon with free shipping and personal recommendations.'
  }
];

export const INITIAL_CAMPAIGNS = [
  {
    id: 'camp-101',
    name: 'Summer Linen & Ethnic Carnival',
    productId: 'prod-2',
    productName: 'FabIndia Pure Linen Handcrafted Kurta',
    sku: 'FASH-FAB-204',
    category: 'Fashion',
    targetSegmentId: 'frequent_buyers',
    targetSegmentName: 'Loyal Frequent Shoppers',
    discountPercent: 15,
    originalPrice: 2899,
    promoPrice: 2464,
    costPrice: 1100,
    startDate: '2026-09-15',
    endDate: '2026-10-05',
    status: 'active',
    estimatedUnits: 180,
    actualUnits: 142,
    estimatedRevenue: 443520,
    actualRevenue: 349888,
    estimatedProfit: 245520,
    actualProfit: 193688,
    marginPercent: 55.3,
    inventoryImpact: 'Safe (178 units buffer remaining)',
    inventoryRisk: 'safe',
    notes: 'Exceeding target weekly run-rate with 55.3% gross profit margin retained.',
    createdAt: '2026-09-10T10:30:00Z',
  },
  {
    id: 'camp-102',
    name: 'Diwali Tech Flagship Audio Special',
    productId: 'prod-1',
    productName: 'Sony WH-1000XM5 Wireless Headphones',
    sku: 'ELEC-SNY-101',
    category: 'Electronics',
    targetSegmentId: 'high_value_vips',
    targetSegmentName: 'High-Value VIPs & Affluent',
    discountPercent: 10,
    originalPrice: 29990,
    promoPrice: 26991,
    costPrice: 19500,
    startDate: '2026-09-01',
    endDate: '2026-09-28',
    status: 'completed',
    estimatedUnits: 65,
    actualUnits: 72,
    estimatedRevenue: 1754415,
    actualRevenue: 1943352,
    estimatedProfit: 486915,
    actualProfit: 539352,
    marginPercent: 27.7,
    inventoryImpact: 'Stock fully aligned; restock arrived on schedule',
    inventoryRisk: 'safe',
    notes: 'Campaign outperformed initial target by 10.8% with zero stockout disruption.',
    createdAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'camp-103',
    name: 'Clearance Blitz: Portable Audio',
    productId: 'prod-10',
    productName: 'boAt Stone 1200 14W Portable Bluetooth Speaker',
    sku: 'ELEC-BOAT-115',
    category: 'Electronics',
    targetSegmentId: 'discount_sensitive',
    targetSegmentName: 'Bargain & Promo Hunters',
    discountPercent: 25,
    originalPrice: 3499,
    promoPrice: 2624,
    costPrice: 1450,
    startDate: '2026-09-20',
    endDate: '2026-10-10',
    status: 'active',
    estimatedUnits: 120,
    actualUnits: 88,
    estimatedRevenue: 314880,
    actualRevenue: 230912,
    estimatedProfit: 140880,
    actualProfit: 103312,
    marginPercent: 44.7,
    inventoryImpact: 'Comfortable stock level',
    inventoryRisk: 'safe',
    notes: 'Liquidating warehouse batch to make room for upcoming Q4 audio range.',
    createdAt: '2026-09-18T09:15:00Z',
  },
  {
    id: 'camp-104',
    name: 'Ayurvedic Radiance VIP Showcase',
    productId: 'prod-4',
    productName: 'Forest Essentials Ayurvedic Soundarya Serum',
    sku: 'BEAU-FOR-405',
    category: 'Beauty & Personal Care',
    targetSegmentId: 'high_value_vips',
    targetSegmentName: 'High-Value VIPs & Affluent',
    discountPercent: 12,
    originalPrice: 4200,
    promoPrice: 3696,
    costPrice: 1800,
    startDate: '2026-10-08',
    endDate: '2026-10-22',
    status: 'scheduled',
    estimatedUnits: 45,
    actualUnits: 0,
    estimatedRevenue: 166320,
    actualRevenue: 0,
    estimatedProfit: 85320,
    actualProfit: 0,
    marginPercent: 51.3,
    inventoryImpact: 'Safe buffer of 40 units remaining after promo',
    inventoryRisk: 'safe',
    notes: 'Scheduled for upcoming festive pre-booking window.',
    createdAt: '2026-09-28T16:20:00Z',
  },
  {
    id: 'camp-105',
    name: 'Reactivation Special: Cold Brew Discovery',
    productId: 'prod-6',
    productName: 'Sleepy Owl Cold Brew Dark Roast Brew Packs',
    sku: 'GROC-SLP-502',
    category: 'Groceries & Gourmet',
    targetSegmentId: 'churn_risk',
    targetSegmentName: 'Lapsed & At-Risk Customers',
    discountPercent: 20,
    originalPrice: 650,
    promoPrice: 520,
    costPrice: 320,
    startDate: '2026-10-12',
    endDate: '2026-10-26',
    status: 'draft',
    estimatedUnits: 150,
    actualUnits: 0,
    estimatedRevenue: 78000,
    actualRevenue: 0,
    estimatedProfit: 30000,
    actualProfit: 0,
    marginPercent: 38.5,
    inventoryImpact: 'Ample inventory (480 in stock)',
    inventoryRisk: 'safe',
    notes: 'Draft awaiting final marketing copy alignment.',
    createdAt: '2026-09-29T11:00:00Z',
  }
];

export const INITIAL_AI_RECOMMENDATIONS = [
  {
    id: 'rec-1',
    productId: 'prod-9',
    productName: 'Minimalist 10% Niacinamide Face Serum',
    sku: 'BEAU-MIN-412',
    category: 'Beauty & Personal Care',
    targetSegmentId: 'frequent_buyers',
    targetSegmentName: 'Loyal Frequent Shoppers',
    recommendedDiscount: 15,
    currentStock: 540,
    forecastDemand: 220,
    currentMarginPercent: 64.9,
    projectedMarginPercent: 58.8,
    projectedRevenue: 112013,
    projectedProfit: 65813,
    inventoryVerdict: 'High Safety (320 units buffer remaining)',
    riskLevel: 'low',
    type: 'Opportunity',
    badge: 'High Margin Surplus',
    title: 'High-Margin Inventory Surplus Clearance',
    rationale: 'Stock is currently 3.6x above reorder threshold with an exceptional 64.9% gross margin. Running a 15% discount for Frequent Shoppers will boost basket velocity while retaining a robust 58.8% gross margin and zero stockout risk.',
    actionLabel: 'Load into Planner'
  },
  {
    id: 'rec-2',
    productId: 'prod-3',
    productName: 'Philips Digital Air Fryer HD9252',
    sku: 'HOME-PHI-309',
    category: 'Home & Kitchen',
    targetSegmentId: 'occasional_shoppers',
    targetSegmentName: 'Occasional Shoppers',
    recommendedDiscount: 0,
    currentStock: 28,
    forecastDemand: 45,
    currentMarginPercent: 43.5,
    projectedMarginPercent: 43.5,
    projectedRevenue: 0,
    projectedProfit: 0,
    inventoryVerdict: 'Critical Deficit (-17 units below projected demand)',
    riskLevel: 'high',
    type: 'Stockout Warning',
    badge: 'Suppress Promotion',
    title: 'Avoid Promotion — Imminent Stockout Hazard',
    rationale: 'Available stock is only 28 units against a 30-day baseline demand of 96 units and lead time of 14 days. Any discount above 5% will trigger a complete stockout within 6 days. Recommend pausing all active ad spend and expediting purchase order PO-884.',
    actionLabel: 'Review Inventory'
  },
  {
    id: 'rec-3',
    productId: 'prod-7',
    productName: 'Puma Velocity Nitro 3 Running Shoes',
    sku: 'FASH-PUM-211',
    category: 'Fashion',
    targetSegmentId: 'high_value_vips',
    targetSegmentName: 'High-Value VIPs & Affluent',
    recommendedDiscount: 12,
    currentStock: 42,
    forecastDemand: 25,
    currentMarginPercent: 53.3,
    projectedMarginPercent: 47.0,
    projectedRevenue: 197978,
    projectedProfit: 92978,
    inventoryVerdict: 'Moderate Buffer (17 units safety stock)',
    riskLevel: 'medium',
    type: 'Targeted Niche',
    badge: 'VIP Segment Match',
    title: 'Niche Premium Push for High-Value Segment',
    rationale: 'High-Value VIP segment exhibits strong affinity for premium footwear with low price elasticity (0.35). A modest 12% privilege discount creates urgency without triggering rapid stock exhaustion before the next shipment.',
    actionLabel: 'Load into Planner'
  }
];

export const SALES_TREND_DATA = [
  { date: 'Sep 01', revenue: 142000, profit: 54000, promoRevenue: 48000, target: 130000 },
  { date: 'Sep 04', revenue: 165000, profit: 62000, promoRevenue: 59000, target: 140000 },
  { date: 'Sep 07', revenue: 158000, profit: 58000, promoRevenue: 52000, target: 145000 },
  { date: 'Sep 10', revenue: 189000, profit: 71000, promoRevenue: 78000, target: 150000 },
  { date: 'Sep 13', revenue: 215000, profit: 84000, promoRevenue: 98000, target: 160000 },
  { date: 'Sep 16', revenue: 198000, profit: 76000, promoRevenue: 85000, target: 165000 },
  { date: 'Sep 19', revenue: 242000, profit: 94000, promoRevenue: 118000, target: 175000 },
  { date: 'Sep 22', revenue: 268000, profit: 106000, promoRevenue: 142000, target: 180000 },
  { date: 'Sep 25', revenue: 235000, profit: 91000, promoRevenue: 110000, target: 185000 },
  { date: 'Sep 28', revenue: 289000, profit: 115000, promoRevenue: 164000, target: 190000 },
  { date: 'Sep 30', revenue: 312000, profit: 124000, promoRevenue: 182000, target: 200000 },
];

export const INITIAL_SETTINGS = {
  storeName: 'Apex Retail Lifestyle & Tech India',
  storeId: 'APX-IN-BLR-01',
  primaryRegion: 'Pan-India (B2C & Omni)',
  currency: 'INR',
  currencySymbol: '₹',
  minGrossMarginThreshold: 18.0, // Minimum profit margin percentage required
  defaultSafetyBufferPercent: 20.0, // Buffer % of stock that should not be consumed by promo
  autoGuardrailsEnabled: true, // Auto-block promotions causing stockout or margin breach
  emailAlertsOnStockout: true,
  autoApprovalThresholdInr: 500000,
  fiscalYearStartMonth: 'April',
};
